name: Build and Push User Service

on:
  push:
    branches: 
      - dev
    paths:
      - 'services/user-service/**'

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: user-service-dev
  SERVICE_NAME: user-service
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::097324129341:role/github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        working-directory: ./services/user-service
        run: |
          docker build -t $ECR_REPOSITORY:$TAG .
          docker tag $ECR_REPOSITORY:$TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$TAG
          docker tag $ECR_REPOSITORY:$TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
