name: Terraform Deploy

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  opentofu:
    name: Deploy with OpenTofu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name != 'pull_request'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::097324129341:role/github-actions-deploy
          aws-region: ap-southeast-2

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: v1.9.1

      - name: Generate tfvars file
        run: |
          cat <<EOF > terraform.tfvars
          environment = "dev"
          instance_type = "t3.micro"
          db_password = "${{ secrets.DB_PASSWORD }}"
          EOF
          
      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Validate
        run: tofu validate

      - name: OpenTofu Plan
        run: tofu plan -out=tfplan

      - name: OpenTofu Apply
        if: github.ref == 'refs/heads/main'
        run: tofu apply -auto-approve tfplan
